"""empty message

Revision ID: 7f3dcbedf1f2
Revises: 
Create Date: 2023-06-07 11:35:44.174446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3dcbedf1f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('casas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotes')
    op.drop_table('casas')
    op.drop_table('users')
    # ### end Alembic commands ###
